# Meant to be imported. See README.

matches:
  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Kaomojis
  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: ":wat"
    replace: "(」°ロ°)」"
  - trigger: ":doubt"
    replace: "(￢_￢)"
  - trigger: ":hug"
    replace: "(づ ◕‿◕ )づ"
  - trigger: ":browraise"
    replace: "( ͠° ͟ʖ ͡°)"
  - trigger: ":happy"
    replace: "＼(￣▽￣)／"
  - trigger: ":content"
    replace: "⸜( ´ ꒳ ` )⸝"
  - trigger: ":smallsmile"
    replace: "ᵕ̈"

  # Copied link
  - trigger: ":l:"
    replace: "[]({{clip}})"
    vars:
      - name: "clip"
        type: "clipboard"

  # Copied link w/ hyperlink text
  - regex: ":l(?P<desc>[^:]+):"
    replace: "[{{desc}}]({{clip}})"
    vars:
      - name: "clip"
        type: "clipboard"

  # Stars for obsidian
  - trigger: ":stary"
    replace: "<font color=\"#fff98a\">✩</font> "
  - trigger: ":staro"
    replace: "<font color=\"#fcb968\">✩</font> "
  - trigger: ":starr"
    replace: "<font color=\"#fc5858\">✩</font> "
